### PR TITLE
build: slim down the docker container

### PR DESCRIPTION
**Pull request by VitalyArt**
| Image | Size |
|-------|--------|
| original | 583MB |
| new  | 289MB |

### CODE REVIEW

**Comment by alexandreteles** [comment]
Please modify your commit to follow the semantic standard. Something like `refactor: optimize dockerfile` should be fine.

**Comment by oSumAtrIX** [comment]
@alexandreteles A squash merge allows to specify the commit message

**Comment by alexandreteles** [comment]
> @alexandreteles A squash merge allows to specify the commit message

I know, I'm trying to enforce contribution rules about how commits should be named. The PR would be ultimately merged.

**Comment by oSumAtrIX** [comment]
@alexandreteles In this case contribution guidelines should be present and PRs blocked when they can not be squashed to fix the issue.

**Comment by VitalyArt** [comment]
> Please modify your commit to follow the semantic standard. Something like `refactor: optimize dockerfile` should be fine.

done

**Comment by VitalyArt** [comment]
@alexandreteles @oSumAtrIX ping

**Comment by alexandreteles** [comment]
Will be merged soon. I've been too busy to work on the new features and integrate your PR but I will look into it either this weekend or next week.

**Review by alexandreteles — APPROVED** [review]

**Pull request merged**
