### PR TITLE
feat: added branding

### PR DESCRIPTION
**Pull request by BenjaminHalko**
Added brand link to the `/info` section

### CODE REVIEW

**Comment by Ushie** [comment]
The API should not house all assets, as it's not designed to function like a CDN. The overarching plan is to enable users to fork the API and incorporate their own logos. Therefore, including logo variants in the API doesn't align with this strategy. There's no guarantee that forks will maintain our logo variants. To ensure consistency, we should retain a single, definitive logo as our base variant

**Comment by BenjaminHalko** [comment]
So we should only show the one circular logo in the API?

**Comment by oSumAtrIX** [comment]
In our case, that would be the main one, yeah.

**Review by oSumAtrIX — APPROVED** [review]

**Comment by Ushie** [comment]
Why do we need "branding scalability"? it's a singular logo

**Review by alexandreteles — APPROVED** [review]

**Comment by alexandreteles** [comment]
> Why do we need "branding scalability"? it's a singular logo

The current implementation returns only a single logo. I think this matches the proposed changes, and the code is okay and should be ready to merge. I will wait for your review before doing so, tho.

**Review by Ushie — APPROVED** [review]

**Pull request merged**
